# The Mynt daemon and Mynt RCP client IP and port.
daemon = "127.0.0.1:24090"
rpc = "127.0.0.1:22092"

# Your Mynt RPC client username and password.
username = "onodera"
password = "seekrit"

# The IP and port to host sako on.
host = "127.0.0.1:8080"

# The currency to compare XSM to, choose between `USD` or `EUR`.
currency = "USD"
